# Personal Mosquitto Config

# Allow for anonymous connections
allow_anonymous true

# Save the in memory database to disc every 15 minutes
autosave_interval 900

# Save the subscription changes
autosave_on_changes true

# Persistent data (connection, subscription, message, et al)
persistence true

# Persistence Filename
persistence_file mosquitto-persist.db

# Perisitent Client Clean Up
persistent_client_expiration 14d

# Listeners (most specific first)
# listen on port 1883 on IP address 10.25.35.101
#
# Use ipconfig (on Windows) to find out the local machine
# IP Address and update the value here. If you have more
# than one network connection, duplicate the line and
# update the IP address for each one
listener 1883 10.25.35.101
# listen on port 1883 on all IP addresses of this machine
# this usually works for all network connections, but we
# are adding as a fall back.
listener 1883 0.0.0.0

# maximum number of clients that can connect to the broker
max_connections 16